### ISSUE TITLE
build fails @ 73% error: unknown type name = empower-openairinterface 

### ISSUE THREAD

**Issue by WindyCitySDR** [5g-empower/empower-openairinterface#1]
Hello,

I've been trying to compile empower-openairinterface, but it keeps failing on:  **error: unknown type name**

**Here is what I am running:**

ubuntu@ubuntu:~/empower-openairinterface/cmake_targets$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Here is my cmake version:**

ubuntu@ubuntu:~/empower-openairinterface/cmake_targets$ cmake --version
cmake version 2.8.12.2

**Here is my pkg-config version:**

ubuntu@ubuntu:~/empower-openairinterface/cmake_targets$ pkg-config --modversion glib-2.0
2.40.2

**Here is my kernel version:**

ubuntu@ubuntu:~/empower-openairinterface/cmake_targets$  cat /proc/version

Linux version 3.19.0-25-generic (buildd@lgw01-20) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015

**Here are the pkg-config libraries I have installed:**

ubuntu@ubuntu:~/empower-openairinterface/cmake_targets$ pkg-config --libs --cflags gtk+-3.0
-pthread -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12  -lgtk-3 -lgdk-3 -latk-1.0 -lgio-2.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lpango-1.0 -lcairo -lgobject-2.0 -lglib-2.0 

**Here is the Git version branch I've downloaded/running:**

ubuntu@ubuntu:~/empower-openairinterface/cmake_targets$ cd .. && git log -n1

commit 42c80b2a0b5d53cacae9695e92d60135c7e5ca0b
Author: herlesupreeth <herlesupreeth@gmail.com>
Date:   Tue Nov 15 11:18:27 2016 +0100
Changes to config file as per features introduced in develop branch of OAI5G Eurecom repo

**Here is the actual log where it fails to build 100%**

ubuntu@ubuntu:~/empower-openairinterface/cmake_targets$ sudo ./build_oai --cflags_processor "-mssse3 -msse4.1 -mavx2" --verbose-compile -I -g --eNB -x --install-system-files --install-external-packages --install-optional-packages -w USRP

/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c: In function ‘emoai_UEs_ID_report’:
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:141:2: error: unknown type name ‘ActiveUe’
  ActiveUe **active_ue_id = NULL;
  ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:142:2: error: unknown type name ‘InactiveUe’
  InactiveUe **inactive_ue_id = NULL;
  ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:149:23: error: ‘ActiveUe’ undeclared (first use in this function)
                sizeof(ActiveUe *));
                       ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:149:23: note: each undeclared identifier is reported only once for each function it appears in
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:149:33: error: expected expression before ‘)’ token
                sizeof(ActiveUe *));
                                 ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:151:5: warning: implicit declaration of function ‘active_ue__init’ [-Wimplicit-function-declaration]
     active_ue__init(active_ue_id[n_active_ue_id - 1]);
     ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:152:37: error: request for member ‘rnti’ in something not a structure or union
     active_ue_id[n_active_ue_id - 1]->rnti = emoai_get_ue_crnti(i);
                                     ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:153:37: error: request for member ‘imsi’ in something not a structure or union
     active_ue_id[n_active_ue_id - 1]->imsi = emoai_get_ue_imsi(i);
                                     ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:154:37: error: request for member ‘plmn_id’ in something not a structure or union
     active_ue_id[n_active_ue_id - 1]->plmn_id =
                                     ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:159:36: error: ‘InactiveUe’ undeclared (first use in this function)
          n_inactive_ue_id * sizeof(InactiveUe *));
                                    ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:159:48: error: expected expression before ‘)’ token
          n_inactive_ue_id * sizeof(InactiveUe *));
                                                ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:162:5: warning: implicit declaration of function ‘inactive_ue__init’ [-Wimplicit-function-declaration]
     inactive_ue__init(inactive_ue_id[n_inactive_ue_id - 1]);
     ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:163:41: error: request for member ‘rnti’ in something not a structure or union
     inactive_ue_id[n_inactive_ue_id - 1]->rnti =
                                         ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:165:41: error: request for member ‘imsi’ in something not a structure or union
     inactive_ue_id[n_inactive_ue_id - 1]->imsi =
                                         ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:167:41: error: request for member ‘plmn_id’ in something not a structure or union
     inactive_ue_id[n_inactive_ue_id - 1]->plmn_id =
                                         ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:175:6: error: ‘UesIdRepl’ has no member named ‘n_active_ue_id’
  repl->n_active_ue_id = n_active_ue_id;
      ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:176:6: error: ‘UesIdRepl’ has no member named ‘active_ue_id’
  repl->active_ue_id = active_ue_id;
      ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:177:6: error: ‘UesIdRepl’ has no member named ‘n_inactive_ue_id’
  repl->n_inactive_ue_id = n_inactive_ue_id;
      ^
/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c:178:6: error: ‘UesIdRepl’ has no member named ‘inactive_ue_id’
  repl->inactive_ue_id = inactive_ue_id;
      ^
make[3]: *** [CMakeFiles/WRAP_LIB.dir/home/ubuntu/empower-openairinterface/emage_tech_oai/emoai_config.c.o] Error 1
make[3]: Leaving directory `/home/ubuntu/empower-openairinterface/cmake_targets/lte_build_oai/build'
make[2]: *** [CMakeFiles/WRAP_LIB.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....

Both my EPC and HSS are fully built 100% cleanly.

**Do I have to add #include <stdint.h> to emoai_config.c, or any other empower-openairinterface files to get this to build 100% ?**

**Comment by herlesupreeth** [comment]
Hello,

Thank you for bringing this issue to my notice. Its a bug. I have the fix for it and I will push it by the end of the day.

No, it not the problem with including #include <stdint.h>.

After I push the changes to emage branch, could you please do a pull on both empower-enb-agent and empower-openairinterface repo and recompile and let me know?

Thanks and Regards,
Supreeth

**Comment by herlesupreeth** [comment]
Hello,

Sorry, i didn't realize earlier. I see that you are on a older git commit, could you please do a git pull on the "develop" branch of empower-openairinterface and give it a try?

Regards,
Supreeth

**Comment by WindyCitySDR** [comment]
Supreeth,



Per your instructions, I downloaded a fresh copy of your Develop branch, and everything compiles/builds without any error.

Thank you sincerely!
